# Generated by Django 4.2 on 2024-04-02 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermovierating',
            name='watched',
            field=models.BooleanField(default=False),
        ),
    ]
