# Generated by Django 4.2 on 2024-04-02 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_movie_age_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermovierating',
            name='rating',
            field=models.FloatField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
    ]
