# Generated by Django 4.2 on 2024-04-04 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_usermovierating_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermovierating',
            name='watched',
        ),
    ]
